### ISSUE TITLE
Error en el login del proyecto

### ISSUE THREAD

**Issue by emiarias** [ACarrera/burgerCode#51]
No se puede usar el login del proyecto, ni registrar nuevos usuarios

![image](https://user-images.githubusercontent.com/18445151/204000851-ebf05fd0-a1b8-4af1-a78d-875bd8b916f1.png)

**Comment by nahueldelavega** [comment]
problema resuelto!

**Comment by emiarias** [comment]
Buenas @nahueldelavega el problema aun persiste, si realizaron cambios asegurense que este actualizado en netlify. Actualmente sigue si n funcionar el login

![image](https://user-images.githubusercontent.com/18445151/208119724-c2019280-9387-48ee-861c-63180d634a72.png)
