### ISSUE TITLE
No se visualiza correctamente las opciones del menú en dispositivos small y medium

### ISSUE THREAD

**Issue by emiarias** [ACarrera/burgerCode#73]
Corregir la vista del navbar en dispositivos pequeños y medianos

![image](https://user-images.githubusercontent.com/18445151/208118017-127d246d-c6d1-4dbc-82e1-e6463620a7f9.png)

![image](https://user-images.githubusercontent.com/18445151/208118348-ef821714-45e3-4a0e-825e-5383c5031506.png)

**Comment by MCeciliaLuna** [comment]
Corregido!
