### ISSUE TITLE
El login de usuario no funciona

### ISSUE THREAD

**Issue by emiarias** [ACarrera/burgerCode#74]
Buenas @nahueldelavega el problema aun persiste, si realizaron cambios asegurense que este actualizado en netlify. Actualmente sigue si n funcionar el login

![image](https://user-images.githubusercontent.com/18445151/208119724-c2019280-9387-48ee-861c-63180d634a72.png)

_Originally posted by @earias08 in https://github.com/ACarrera/burgerCode/issues/51#issuecomment-1354936025_

**Comment by MCeciliaLuna** [comment]
Corregido!
